name: animu
description: Companion App for Animu Discord Bot

version: 0.5+10

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  http: ^0.12.0+2
  bubble_bottom_bar: ^1.2.0
  charts_flutter: ^0.8.1
  timeago: ^2.0.22
  gradient_widgets: ^0.5.0
  flutter_launcher_icons: '^0.7.3'
  flutter_chips_input: ^1.6.0
  flutter_speed_dial: ^1.2.4
  font_awesome_flutter: ^8.5.0
  url_launcher: ^5.2.7
  bloc: ^2.0.0
  flutter_bloc: ^2.0.0
  qr_code_scanner: ^0.0.12
  animu_common:
    path: ../animu_common

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: 'ic_launcher'
  ios: true
  image_path: 'assets/logo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
